/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppOnboardingRouteImport } from './routes/_authenticated/app.onboarding'
import { Route as AuthenticatedAppRecordsIndexRouteImport } from './routes/_authenticated/app.records.index'
import { Route as AuthenticatedAppRecordsIdRouteImport } from './routes/_authenticated/app.records.$id'
import { Route as AuthenticatedAppRecordsNewRouteImport } from './routes/_authenticated/app.records.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOnboardingRoute =
  AuthenticatedAppOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRecordsIndexRoute =
  AuthenticatedAppRecordsIndexRouteImport.update({
    id: '/records/',
    path: '/records/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRecordsIdRoute =
  AuthenticatedAppRecordsIdRouteImport.update({
    id: '/records/$id',
    path: '/records/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRecordsNewRoute =
  AuthenticatedAppRecordsNewRouteImport.update({
    id: '/records/new',
    path: '/records/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/records/$id': typeof AuthenticatedAppRecordsIdRoute
  '/app/records/new': typeof AuthenticatedAppRecordsNewRoute
  '/app/records/': typeof AuthenticatedAppRecordsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/records/$id': typeof AuthenticatedAppRecordsIdRoute
  '/app/records/new': typeof AuthenticatedAppRecordsNewRoute
  '/app/records': typeof AuthenticatedAppRecordsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/disclaimer': typeof DisclaimerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/records/$id': typeof AuthenticatedAppRecordsIdRoute
  '/_authenticated/app/records/new': typeof AuthenticatedAppRecordsNewRoute
  '/_authenticated/app/records/': typeof AuthenticatedAppRecordsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/disclaimer'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/app'
    | '/app/onboarding'
    | '/app/'
    | '/app/records/$id'
    | '/app/records/new'
    | '/app/records/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/disclaimer'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/app/onboarding'
    | '/app'
    | '/app/records/$id'
    | '/app/records/new'
    | '/app/records'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/disclaimer'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/_authenticated/app'
    | '/_authenticated/app/onboarding'
    | '/_authenticated/app/'
    | '/_authenticated/app/records/$id'
    | '/_authenticated/app/records/new'
    | '/_authenticated/app/records/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DisclaimerRoute: typeof DisclaimerRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/onboarding': {
      id: '/_authenticated/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AuthenticatedAppOnboardingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/records/': {
      id: '/_authenticated/app/records/'
      path: '/records'
      fullPath: '/app/records/'
      preLoaderRoute: typeof AuthenticatedAppRecordsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/records/$id': {
      id: '/_authenticated/app/records/$id'
      path: '/records/$id'
      fullPath: '/app/records/$id'
      preLoaderRoute: typeof AuthenticatedAppRecordsIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/records/new': {
      id: '/_authenticated/app/records/new'
      path: '/records/new'
      fullPath: '/app/records/new'
      preLoaderRoute: typeof AuthenticatedAppRecordsNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppOnboardingRoute: typeof AuthenticatedAppOnboardingRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppRecordsIdRoute: typeof AuthenticatedAppRecordsIdRoute
  AuthenticatedAppRecordsNewRoute: typeof AuthenticatedAppRecordsNewRoute
  AuthenticatedAppRecordsIndexRoute: typeof AuthenticatedAppRecordsIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppOnboardingRoute: AuthenticatedAppOnboardingRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppRecordsIdRoute: AuthenticatedAppRecordsIdRoute,
  AuthenticatedAppRecordsNewRoute: AuthenticatedAppRecordsNewRoute,
  AuthenticatedAppRecordsIndexRoute: AuthenticatedAppRecordsIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DisclaimerRoute: DisclaimerRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
